### ISSUE TITLE
feature: Zap support

### ISSUE THREAD

**Issue by 0xtrr** [0xtrr/nostr-tool#38]
I have not done too much thinking about this but adding it so I, or someone else, can take a look at it later. Does it make sense to support Zaps in nostr-tool?

**Comment by Asone** [comment]
As far as i digged, Zap is not supported yet natively in the `nostr-sdk`. I couldn't find any reference to NIP-57, be it in the issues or in the code. 

I guess there is a way to implement its support, but it would make sense to design it for the SDK first and use the implementation rather than creating an external implementation.

**Comment by thesimplekid** [comment]
I used `nostr-sdk` for https://github.com/thesimplekid/cln-zapper-rs and was thinking it would make sense to upstream some of it didn't just to get it working. But plan to take another look.

**Comment by thesimplekid** [comment]
https://github.com/rust-nostr/nostr/pull/69

**Comment by thesimplekid** [comment]
https://github.com/rust-nostr/nostr/pull/72

**Comment by 0xtrr** [comment]
Fixed in #47.
